[phases.setup]
nixPkgs = ["nodejs-20_x", "bun"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["reflex init", "reflex export --no-zip"]

[start]
cmd = "reflex run --env prod"
